config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'static#index'
  get '/users' => 'users#index'
  devise_for :users, :controllers => {:registrations => "user/registrations"}
  resources :users do
    resources :friendships, only: [:index, :update, :destroy, :new, :create]
    resources :posts, only: [:index, :create]
  end

end

app/models/friendship.rb
class Friendship < ApplicationRecord
  validates_presence_of :sender, :receiver
  validates :sender, uniqueness: {scope: :receiver}
  validates :receiver, uniqueness: {scope: :sender}
  validate :cant_friend_self

  belongs_to :sender, class_name: "User"
  belongs_to :receiver, class_name: "User"

  def cant_friend_self
    errors.add(:sender, "You cannot friend yourself!!") if self.sender == self.receiver
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  skip_before_action :verify_authenticity_token

  # def new
  #   @receiver = User.find_by(id: params[:id].to_i)
  # end

  def create
    @user = User.find_by(id: params[:user_id])
    @sender = current_user
    @friendship = Friendship.new(receiver: @user, sender: @sender)
    if @friendship.save
      redirect_to '/'
    else
      render 'posts/index'
    end
  end

  # show a list of friends and pending requests
  # def index

  # 	@friends = current_user.friends
  # 	@pending_incoming = current_user.pending_incoming_requests
  # 	@pending_outgoing =	current_user.pending_outgoing_requests
  # end


  def update


  	@friendship = current_user.friendships_1.find_by(sender_id: params[:id])
  	# binding.pry
  	@friendship.update_attributes(accepted: true)


   redirect_to root_url
   #redirect to the index page

  end

  def destroy

  	@friendship = current_user.friendships_1.find_by(sender_id: params[:id])
  	@friendship.destroy
  	redirect_to root_url
  	#redirect to the index page
  end


end

app/helpers/friendships_helper.rb
module FriendshipsHelper
  def invitable?(user)
    current_user.friends.index(user) == nil && current_user != user
  end

  def own_list?(user)
    current_user == user
  end

end

app/views/friendships/_index.html.erb
<h3>Friend List</h3>

<div>
	<% if own_list?(@user) %>
	<p>
		<label>Your Friend list</label>
		<% current_user.friends.each do |friend|%>
		  <%= link_to friend.username, user_posts_path(friend) %><br>

		  <!-- remember to add link to the name to go to friend`s profile -->

		<% end %>
	</p>

	<p>
		<label> Incoming Request</label>
		<% current_user.pending_incoming_requests.each do |friendrequest|%>
		  <%= friendrequest.username %><br>

		<%= button_to 'Add this person', user_friendship_path(current_user,friendrequest),:method => :patch %>

		 <%= button_to 'Go Away', user_friendship_path(current_user,friendrequest),:method => :delete   %>

		<% end %>
	</p>

	<p>
		<label>Outgoing Request</label>
		<% current_user.pending_outgoing_requests.each do |friendrequest|%>
		  <%= friendrequest.username %><br>
		<% end %>
	</p>
	<% else %>
		<p>
			<label>Your Friend list</label>
			<% @user.friends.each do |friend|%>
			  <%= link_to friend.username, user_posts_path(friend) %><br>

			  <!-- remember to add link to the name to go to friend`s profile -->

			<% end %>
		</p>

	<% end %>

</div>

app/views/friendships/_new.html.erb
<div class="container">

  <section class="sidebar">
    <% if @friendship %>
      <ul>
        <% @friendship.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    <% end %>

    <form id="friend_request" action="/users/<%= @user.id %>/friendships" method="post">
      <input type="submit" value="invite friend">
    </form>
  </section>

  <main class="friend">
    <div class="sign-text-wrap">
      <div class="sign-text">

        <% if @friends %>
          <span><%= @friends %></span>
        <% end %>

      </div>
    </div>
  </main>
</div>

app/views/friendships/index.html.erb
<h3>Friend List</h3>

<div>
	<p>
		<label>Your Friend list</label>
		<% @friends.each do |friend|%>
		  <%= friend.username %><br>

		  <!-- remember to add link to the name to go to friend`s profile -->
		  
		<% end %>
	</p>

	<p>
		<label> Incoming Request</label>
		<% @pending_incoming.each do |friendrequest|%>
		  <%= friendrequest.username %><br>

		<%= button_to 'Add this person', user_friendship_path(current_user,friendrequest),:method => :patch %>

		 <%= button_to 'Go Away', user_friendship_path(current_user,friendrequest),:method => :delete   %>

		<% end %>
	</p>

	<p>
		<label>Outgoing Request</label>
		<% @pending_outgoing.each do |friendrequest|%>
		  <%= friendrequest.username %><br>
		<% end %>
	</p>

</div>

app/views/friendships/new.html.erb
<div class="container">

  <section class="sidebar">
    <% if @friendship %>
      <ul>
        <% @friendship.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    <% end %>

    <form id="friend_request" action="/users/<%= @receiver.id %>/friendships" method="post">
      <input type="submit" value="invite friend">
    </form>
  </section>

  <main class="friend">
    <div class="sign-text-wrap">
      <div class="sign-text">

        <% if @friends %>
          <span><%= @friends %></span>
        <% end %>

      </div>
    </div>
  </main>
</div>